name: Build PlotSquared v7

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 关键步骤 1: 全局注入备用仓库
      - name: Configure Gradle with Mirrors
        run: |
          mkdir -p ~/.gradle
          echo "allprojects {
              repositories {
                  maven { url 'https://maven.aliyun.com/repository/public' }
                  maven { url 'https://repo.papermc.io/repository/maven-public/' }
                  mavenCentral()
                  google()
              }
          }" > ~/.gradle/init.gradle
          
      # 关键步骤 2: 从项目配置中移除故障仓库
      - name: Remove problematic EngineHub repository from config
        run: sed -i "/maven.enginehub.org/d" settings.gradle.kts
          
      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PlotSquared-v7-JARs
          path: '**/build/libs/!(*-javadoc|*-sources).jar'
